### ISSUE TITLE
kinobrom.ru

### ISSUE THREAD

**Issue by tensey2** [dle-modules/DLE-EditRating#1]
Привет, установил твой рейтинг кнопка появилась в том месте где хотел но не нажимается. При нажатии ничего не происходит. Выручай..

**Comment by pafnuty** [comment]
Где можно наблюдать ошибку?

**Comment by tensey2** [comment]
я посмотрел, кодировка может не та, я думаю это роли не играет, просто при нажатии нет ничего

**Comment by pafnuty** [comment]
Я понял, что что-то не работает, но к сожалению не обладаю телепатическими способностями и не могу увидеть ошибку. Где можно наблюдать ошибку?

**Comment by tensey2** [comment]
что от меня требуется?

**Comment by tensey2** [comment]
<!DOCTYPE html>
<html lang="ru">
<head>
{headers}
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="shortcut icon" href="{THEME}/images/favicon.png" />
  <link href="{THEME}/style/styles.css" type="text/css" rel="stylesheet" />
  <link href="{THEME}/style/engine.css" type="text/css" rel="stylesheet" />
  
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,500,700,400italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
   <link media="screen" href="{THEME}/comm/style.css" type="text/css" rel="stylesheet" /> 
    
   
<link rel="stylesheet" href="/engine/classes/min/index.php?charset=utf-8&amp;f={THEME}/editrating/css/editrating.css&amp;01" />
<script type="text/javascript" src="/engine/classes/min/index.php?charset=utf-8&amp;f={THEME}/editrating/js/jquery.magnificpopup.min.js,{THEME}/editrating/js/jquery.ladda.min.js,{THEME}/editrating/js/jquery.form.min.js,{THEME}/editrating/js/editrating.js&amp;01"></script>

</head>

**Comment by tensey2** [comment]
`<!DOCTYPE html>
<html lang="ru">
<head>
{headers}
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="shortcut icon" href="{THEME}/images/favicon.png" />
  <link href="{THEME}/style/styles.css" type="text/css" rel="stylesheet" />
  <link href="{THEME}/style/engine.css" type="text/css" rel="stylesheet" />
  
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,500,700,400italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
   <link media="screen" href="{THEME}/comm/style.css" type="text/css" rel="stylesheet" /> 
    
   
<link rel="stylesheet" href="/engine/classes/min/index.php?charset=utf-8&amp;f={THEME}/editrating/css/editrating.css&amp;01" />
<script type="text/javascript" src="/engine/classes/min/index.php?charset=utf-8&amp;f={THEME}/editrating/js/jquery.magnificpopup.min.js,{THEME}/editrating/js/jquery.ladda.min.js,{THEME}/editrating/js/jquery.form.min.js,{THEME}/editrating/js/editrating.js&amp;01"></script>

</head>
`

**Comment by tensey2** [comment]
http://joxi.ru/Vm6aDaeuQeeNrZ

**Comment by tensey2** [comment]
http://joxi.ru/5mdzXzpHYEEoA1

**Comment by tensey2** [comment]
могу доступ предоставить

**Comment by pafnuty** [comment]
Возможно вы недавно начали заниматься сайтостроением,  а я отвык от
новичков. Прошу прощения.
Для диагностики ошибки обычно необходимо её воспроизвести.  Для
воспроизведения ошибки как правило достаточно адреса сайта и логина с
паролем при необходимости.
Пароль и логин можно отправить на почту.
20 июн 2016 г. 18:49 пользователь "tensey2" notifications@github.com
написал:

**Comment by tensey2** [comment]
доступ предоставил на почту зайдите пожалуйста.

**Comment by pafnuty** [comment]
Перенесите js модуля в конец страницы, как вы поступили с другими скриптами.
