### ISSUE TITLE
редактирование "лайк" и "дизлайк"

### ISSUE THREAD

**Issue by serg91100** [dle-modules/DLE-EditRating#2]
---

@pafnuty не забудь посмотреть этот тиккет :ticket:

Здравствуйте. На сайте стоит модифицированный рейтинг в виде лайков (http://sandev.pro/web/86-rasshirenie-funkcionala-standartnogo-reytinga-nravitsya-ne-nravitsya.html)

Ссылка на тестовый сайт http://otzovik.webcoon.ru/admin23212.php
Логин pafnuty
Пароль pafnuty

**Comment by pafnuty** [comment]
Модуль корректно работает со стандартным рейтингом.
Установите стандартный рейтинг. Если есть потребность в модифицированном модуле - лучше обратиться к фрилансерам.
